# Data Prepration

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
#Importing Pandas to handle database
df = pd.read_csv (r'project.csv')
#df is the dataframe which is imported
df.head()
#.head() shows the first 5 rows of the dataframe to look at the data variables and value types

Match_id    Team1     Team2           Venue Toss_winner Toss_decision  \
0    225245  England  Pakistan  Sophia Gardens    Pakistan         field   
1    225246  England  Pakistan          Lord's    Pakistan         field   
2    225247  England  Pakistan   The Rose Bowl    Pakistan         field   
3    225248  England  Pakistan    Trent Bridge    Pakistan           bat   
4    225249  England  Pakistan       Edgbaston     England         field   

     Winner        Players_1      Players_2      Players_3        Players_4  \
0      draw   ME Trescothick     AJ Strauss        IR Bell     KP Pietersen   
1  Pakistan   ME Trescothick     AJ Strauss        IR Bell     KP Pietersen   
2  Pakistan   ME Trescothick        IR Bell     AJ Strauss     KP Pietersen   
3   England  Mohammad Hafeez  Shahid Afridi    Younis Khan  Mohammad Yousuf   
4   England  Mohammad Hafeez   Imran Farhat  Shahid Afridi      Younis Khan   

         Players_5       Players_6     Players_7     Players_8  \
0   PD Collingwood   JWM Dalrymple      R Clarke      CMW Read   
1   PD Collingwood   JWM Dalrymple      R Clarke      CMW Read   
2   PD Collingwood   JWM Dalrymple      R Clarke      CMW Read   
3   Inzamam-ul-Haq    Shoaib Malik  Abdul Razzaq  Kamran Akmal   
4  Mohammad Yousuf  Inzamam-ul-Haq  Abdul Razzaq  Kamran Akmal   

        Players_9      Players_10     Players_11  
0      SI Mahmood       SCJ Broad        D Gough  
1         D Gough         J Lewis      SCJ Broad  
2         J Lewis       SCJ Broad     SI Mahmood  
3   Shoaib Akhtar  Naved-ul-Hasan  Mohammad Asif  
4  Naved-ul-Hasan  Iftikhar Anjum  Mohammad Asif

In [3]:
# running a loop for 2016 because it is the number of rows in the data frame
#In the below loop I wanted to give specefic numer to each team based on their current ICC rankings instead
#of using encoding which assigns a number randomly. Since Playing teams is a feature for the model and in cricket
#the strength of the opposition team matters while playing I gave it a rating from 1 to 9
for i in range(2016):
    if(df['Team1'][i]=='New Zealand'):
        df['Team1'][i] = 1
    elif(df['Team1'][i]=='Australia'):
        df['Team1'][i] = 2
    elif(df['Team1'][i]=='India'):
        df['Team1'][i] = 3
    elif(df['Team1'][i]=='England'):
        df['Team1'][i] = 4
    elif(df['Team1'][i]=='South Africa'):
        df['Team1'][i] = 5
    elif(df['Team1'][i]=='Pakistan'):
        df['Team1'][i] = 6
    elif(df['Team1'][i]=='Bangladesh'):
        df['Team1'][i] = 7
    elif(df['Team1'][i]=='West Indies'):
        df['Team1'][i] = 8
    elif(df['Team1'][i]=='Sri Lanka'):
        df['Team1'][i] = 9
for i in range(2016):
    if(df['Team2'][i]=='New Zealand'):
        df['Team2'][i] = 1
    elif(df['Team2'][i]=='Australia'):
        df['Team2'][i] = 2
    elif(df['Team2'][i]=='India'):
        df['Team2'][i] = 3
    elif(df['Team2'][i]=='England'):
        df['Team2'][i]= 4
    elif(df['Team2'][i]=='South Africa'):
        df['Team2'][i] = 5
    elif(df['Team2'][i]=='Pakistan'):
        df['Team2'][i] = 6
    elif(df['Team2'][i]=='Bangladesh'):
        df['Team2'][i] = 7
    elif(df['Team2'][i]=='West Indies'):
        df['Team2'][i] = 8
    elif(df['Team2'][i]=='Sri Lanka'):
        df['Team2'][i]= 9

In [4]:
#Checking if the changes made are correct
#as it can be seen England is replaced with 4(their rank) and Pakistan with 6
df.head()

Match_id Team1 Team2           Venue Toss_winner Toss_decision    Winner  \
0    225245     4     6  Sophia Gardens    Pakistan         field      draw   
1    225246     4     6          Lord's    Pakistan         field  Pakistan   
2    225247     4     6   The Rose Bowl    Pakistan         field  Pakistan   
3    225248     4     6    Trent Bridge    Pakistan           bat   England   
4    225249     4     6       Edgbaston     England         field   England   

         Players_1      Players_2      Players_3        Players_4  \
0   ME Trescothick     AJ Strauss        IR Bell     KP Pietersen   
1   ME Trescothick     AJ Strauss        IR Bell     KP Pietersen   
2   ME Trescothick        IR Bell     AJ Strauss     KP Pietersen   
3  Mohammad Hafeez  Shahid Afridi    Younis Khan  Mohammad Yousuf   
4  Mohammad Hafeez   Imran Farhat  Shahid Afridi      Younis Khan   

         Players_5       Players_6     Players_7     Players_8  \
0   PD Collingwood   JWM Dalrymple      R Clarke      CMW Read   
1   PD Collingwood   JWM Dalrymple      R Clarke      CMW Read   
2   PD Collingwood   JWM Dalrymple      R Clarke      CMW Read   
3   Inzamam-ul-Haq    Shoaib Malik  Abdul Razzaq  Kamran Akmal   
4  Mohammad Yousuf  Inzamam-ul-Haq  Abdul Razzaq  Kamran Akmal   

        Players_9      Players_10     Players_11  
0      SI Mahmood       SCJ Broad        D Gough  
1         D Gough         J Lewis      SCJ Broad  
2         J Lewis       SCJ Broad     SI Mahmood  
3   Shoaib Akhtar  Naved-ul-Hasan  Mohammad Asif  
4  Naved-ul-Hasan  Iftikhar Anjum  Mohammad Asif

# Data Preprocessing

In [5]:
#importing Libraries that might come in handy later
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [6]:
#Label Encoder is a library which assigns a unique numerical value to every string in a list of strings.
#If a word is present no. of times it is given the same number all the time to maintain data accuracy and veracity
Encoder = LabelEncoder()
venues = Encoder.fit_transform(df['Venue'])
print(venues)

[100  59 105 ... 100  55 106]


In [7]:
#In this loop all the values are updated with their encoded number
for i in range(2016):
    df['Venue'][i] = venues[i]

This Process of the above 2 cells is used below for all the features which will be used in the model

In [8]:
#Using the above process for feature Toss Winner
toss = Encoder.fit_transform(df['Toss_winner'])
print(toss)
for i in range(2016):
    df['Toss_winner'][i] = toss[i]

[5 5 5 ... 4 6 2]


In [9]:
#Using the above process for feature Toss Decision
tossD = Encoder.fit_transform(df['Toss_decision'])
print(tossD)
for i in range(2016):
    df['Toss_decision'][i] = tossD[i]

[1 1 1 ... 1 1 1]


In [10]:
#Using the above process for feature Winner
winner = Encoder.fit_transform(df['Winner'])
print(winner)
for i in range(2016):
    df['Winner'][i] = winner[i]

[9 5 5 ... 4 1 5]


In [11]:
#Checking if the changes are correct
df.head()

Match_id Team1 Team2 Venue Toss_winner Toss_decision Winner  \
0    225245     4     6   100           5             1      9   
1    225246     4     6    59           5             1      5   
2    225247     4     6   105           5             1      5   
3    225248     4     6   106           5             0      2   
4    225249     4     6    41           2             1      2   

         Players_1      Players_2      Players_3        Players_4  \
0   ME Trescothick     AJ Strauss        IR Bell     KP Pietersen   
1   ME Trescothick     AJ Strauss        IR Bell     KP Pietersen   
2   ME Trescothick        IR Bell     AJ Strauss     KP Pietersen   
3  Mohammad Hafeez  Shahid Afridi    Younis Khan  Mohammad Yousuf   
4  Mohammad Hafeez   Imran Farhat  Shahid Afridi      Younis Khan   

         Players_5       Players_6     Players_7     Players_8  \
0   PD Collingwood   JWM Dalrymple      R Clarke      CMW Read   
1   PD Collingwood   JWM Dalrymple      R Clarke      CMW Read   
2   PD Collingwood   JWM Dalrymple      R Clarke      CMW Read   
3   Inzamam-ul-Haq    Shoaib Malik  Abdul Razzaq  Kamran Akmal   
4  Mohammad Yousuf  Inzamam-ul-Haq  Abdul Razzaq  Kamran Akmal   

        Players_9      Players_10     Players_11  
0      SI Mahmood       SCJ Broad        D Gough  
1         D Gough         J Lewis      SCJ Broad  
2         J Lewis       SCJ Broad     SI Mahmood  
3   Shoaib Akhtar  Naved-ul-Hasan  Mohammad Asif  
4  Naved-ul-Hasan  Iftikhar Anjum  Mohammad Asif

# Data Model

In [12]:
#Importing SciKit learning model selection library and importing train_test_split to split dattaset into training
# and testing to train and test the models 
from sklearn.model_selection import train_test_split
# Defining features list with all the variables which will be used in the models
players = ['Players_1','Players_2','Players_3','Players_4','Players_5','Players_6','Players_7','Players_8','Players_9','Players_10','Players_11']

# Importing SVM data model as the first model

In [13]:
#Importing the required libraries
from sklearn import svm
from sklearn.metrics import accuracy_score
#Testing array will contain all the 11 players Y testing list
testing = []
#acr is a variable to store accuracy after every player so average can be calculated
acr = 0

In [14]:
def player_pred(df,player_number,acr) :
    features = ['Team1','Team2','Winner','Toss_decision','Venue']
    X = df.loc[:, features].values
    # Split dataset into training set and test set
    X_train, X_test, y_train, y_test = train_test_split(X, df[players[player_number]], test_size=0.2,random_state=109)
    clf = svm.SVC(kernel='linear',probability=True)
    # Applying the algorith to training data set
    clf.fit(X_train, y_train)
    #adding testing data set to testing array for calculating individual player accuracy
    testing.append(y_test)
    # Predicting the players based on the algorithm
    predicted = clf.predict(X_test)
    #adding algorithm accuracy for predicting this player 
    acr += accuracy_score(y_test, predicted)
    #aranging output predicted players accourding to their probability or likelyness to play
    results = clf.predict_proba(X_test)[0]
    prob_per_class_dictionary = dict(zip(clf.classes_, results))
    res = list(map(lambda x: x[0], sorted(zip(clf.classes_, results), key=lambda x: x[1], reverse=True)))
    #Since sometimes not all 11 players get to play so many cells have - to remove that and take only players and
    # return both the player and its accuracy
    if res[0] != '-':
        return [res[0],acr]
    else:
        return [res[1],acr]

In [15]:
# List which will contain the 11 players 
playing_11 = []

In [16]:
# Loop to run the method 11 times for the 11 players
for i in range (11):
    a = player_pred(df,i,acr)
    playing_11.append(a[0])
    acr = a[1]
#printing the playing 11
print(playing_11)

['WU Tharanga', 'TM Dilshan', 'KC Sangakkara', 'LRPL Taylor', 'EJG Morgan', 'MS Dhoni', 'Shahid Afridi', 'DJG Sammy', 'SCJ Broad', 'M Morkel', 'JM Anderson']


In [17]:
#Printing the accuracy in percentage
print(acr*100, "% is the accuracy of the model")

63.366336633663366 % is the accuracy of the model


In [18]:
#Custom method to find accuracy of individual players
def accuracy(player_number):
    count = 0
    for j in range (11):
        for i in testing[j].values:
            if (i == playing_11[player_number]):
                count += 1
    return count

In [19]:
# Loop to find the accuracy of only the 11 players
sum = 0
for i in range (11):
    sum += accuracy(i)
print((sum/11)/len(testing[0].values)*100)

7.560756075607561


In [20]:
# This method finds the dataset where 2 teams are playing do that a playing 11 can be found when these 2 teams play
def country(country,country2):
    df_country1 = df[(df['Team1']==country) & (df["Team2"]==country2)]
    df_country2 = df[(df['Team1']==country2) & (df["Team2"]==country)]
    frames = [df_country1, df_country2]
    df_country = pd.concat(frames)
    return df_country

In [27]:
#Custom method to take input from user for playing teams
num = int(input("To find a best 11 when New Zeland plays enter 1, To find a best 11 when Australia plays enter 2, \n" + 
                "To find a best 11 when India plays enter 3, To find a best 11 when england plays enter 4, \n" +
                "To find a best 11 when South Africa plays enter 5, \n" +
               "To find a best 11 when Pakistan plays enter 6, To find a best 11 when Bangladesh plays enter 7, \n" +
               "To find a best 11 when West Indies plays enter 8, To find a best 11 when Sri Lanka plays enter 9"))
num2 = int(input("To find a best 11 when New Zeland plays enter 1, To find a best 11 when Australia plays enter 2, \n" + 
                "To find a best 11 when India plays enter 3, To find a best 11 when england plays enter 4, \n" +
                "To find a best 11 when South Africa plays enter 5, \n" +
               "To find a best 11 when Pakistan plays enter 6, To find a best 11 when Bangladesh plays enter 7, \n" +
               "To find a best 11 when West Indies plays enter 8, To find a best 11 when Sri Lanka plays enter 9"))
con = country(num,num2)
playing_11 = []
for i in range (11):
    a = player_pred(con,i,acr)
    playing_11.append(a[0])
    acr = a[1]
print(playing_11)

To find a best 11 when New Zeland plays enter 1, To find a best 11 when Australia plays enter 2, 
To find a best 11 when India plays enter 3, To find a best 11 when england plays enter 4, 
To find a best 11 when South Africa plays enter 5, 
To find a best 11 when Pakistan plays enter 6, To find a best 11 when Bangladesh plays enter 7, 
To find a best 11 when West Indies plays enter 8, To find a best 11 when Sri Lanka plays enter 92
To find a best 11 when New Zeland plays enter 1, To find a best 11 when Australia plays enter 2, 
To find a best 11 when India plays enter 3, To find a best 11 when england plays enter 4, 
To find a best 11 when South Africa plays enter 5, 
To find a best 11 when Pakistan plays enter 6, To find a best 11 when Bangladesh plays enter 7, 
To find a best 11 when West Indies plays enter 8, To find a best 11 when Sri Lanka plays enter 91
['AJ Strauss', 'TD Paine', 'RT Ponting', 'MJ Clarke', 'CL White', 'MEK Hussey', 'SPD Smith', 'B Lee', 'MG Johnson', 'GJ Batty', 